apiVersion: apps/v1
kind: Deployment
metadata:
  name: cheem-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cheem
  template:
    metadata:
      labels:
        app: cheem
    spec:
      containers:
      - image: cheemcheem/cheem:<TAG>
        name: cheem-container
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          failureThreshold: 1
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: cheem-service
spec:
  selector:
     app: cheem
  type: ClusterIP
  ports:
    - name: cheem-port
      port: 80
