# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    name: Test, Build, Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Start NPM Cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-     
               
      - name: Install Node Modules
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Build Project
        run: npm run build
      
      - name: Prepare SSH Key
        if: ${{github.ref == 'refs/heads/develop'}}
        run: 'echo "$SSH_KEY" > key'
        shell: bash
        env:
          SSH_KEY: ${{secrets.KEY}}
      
      - name: Upload Project to Dev Server 
        if: ${{github.ref == 'refs/heads/develop'}}
        run:
          scp -i key -r build/ ${{secrets.USERNAME}}@${{secrets.HOST}}:${{secrets.PATH}}
  
